modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/lukebemish/simple_buffers/issues"
license = "LGPL v3"

[[mods]]
modId = "simple_buffers"
version = "${version}"
displayName = "Simple Buffers"
authors = "Luke Bemish"
description = '''
Simple, configurable item buffers
'''
#logoFile = ""

[[dependencies.simple_buffers]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_buffers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_buffers]]
modId = "architectury"
mandatory = true
versionRange = "[3.3.7,)"
ordering = "AFTER"
side = "BOTH"